code/mumvm/session0/사전학습자료_pandas 입문 (13기).ipynb, code/mumvm/session0/사전학습자료_파이썬 기초 (13기).ipynb
=> [session0] 문유정 과제 제출합니다.

code/yseo17/session0/사전학습자료_pandas 입문 (13기).ipynb, code/yseo17/session0/사전학습자료_파이썬 기초 (13기).ipynb
오랜만에 파이썬을 다시 복습하며 까먹었던 부분들을 다시 공부할 수 있었습니다.
또, 깃을 처음 사용해 보며 기본적인 저장소 개념부터 과제 업로드까지 직접 해볼 수 있었습니다.
=> [session0] 김윤서 과제 제출합니다

code/Jonghyun777/session1/EDA&전처리_마크다운_사전과제.ipynb, code/Jonghyun777/session1/pandas_과제.ipynb
1.4.2번 문항에서 처음에는 &를 사용하여 문제를 풀려고 하였으나, 계속해서 Value error가 발생하였습니다. 결국 loc을 사용하여 문제를 풀긴 했지만,, &를 사용하여 풀 수 있는 방법은 없는지 궁금합니다!
EDA부분 마크다운을 진행하면서 데이터분석에서 EDA가 정말 중요한 거 같다고 느꼈습니다. 이번 교육 세션 열심히 들어야겠다고 생각하였습니다.
=> [session1] 이종현 과제 제출합니다.

code/i-am-jsung/session1/EDA_전처리사전과제_김재성.ipynb, code/i-am-jsung/session1/pandas_과제.ipynb
pandas가 어떤건지 어떻게 쓸 수 있는지 전반적으로 알 수 있었습니다. 어떻게 활용할 지 기대됩니다. 
embark_town과 pclass를 내림차순으로 정렬이 답이랑 다르게 나옵니다 ㅜ
큰 데이터를 다룰 때 EDA, 전처리가 어떻게 활용될지 궁금합니다
=> [seesion1] 김재성 과제 제출합니다.

code/YOUNGJIN-CHO-1/Session2_1/심화세션_앙상블_과제.ipynb
오랜만에 깃허브로 과제 제출하려니까 조금 어색하네요
모델 열심히 만들었는데 성능 개선 폭이 자잘해서 아쉽긴 한데 그래도 최선을 다했습니다
신입 기수로 심화 세션을 진행할 땐 실습과 과제가 세션의 내용과 조금 동떨어져 있다는 느낌을 조금 받았고, 조금 더 구체적으로 다뤄줬으면 좋겠다 싶었는데, 이번에는 배웠던 걸로 실제 모델 구현까지 해볼 수 있어서 매우 좋았습니다. 
최종 성능 0.8840입니당 1등하고 싶어요
=> [session2_1] 조영진 과제 제출합니다.

code/Minhui21/session2_1/김민희_심화세션_앙상블_과제.ipynb
ㅠㅠ 깃헙은 왜이렇게 어려울까요 . . . ? 다음엔 제대로 올려야지  ...
=> [session2_1] 김민희 과제 제출합니다.

code/hyunji1122/session2_1/심화세션_앙상블_과제.ipynb
=> [session2_1] 신현지 과제 제출합니다.

code/yyellow14/session2_3/장바구니 과제.ipynb
용량 이슈로 셀 출력 부분들은 다 삭제되었습니다... 깃헙에 100MB 용량 제한이 있다는 걸 처음 알았어요. 빅분기 시험 볼 때 지지도, 신뢰도, 향상도는 맨날 나오는 문제였는데 헷갈려서 찍었었는데 이번 기회에 확실히 배우고 갑니다 👍. 특히 찬우 씨가 다양한 예시들과 중간중간 의도치 않은 개그들을 하셔서 집중도 잘되고 더 기억에 남는거 같아요 :) 중간에 트리와 링크드 리스트가 결합된 FP-Tree가 나와서 자료구조를 배운 보람을 좀 느꼈습니다.
=> [session2_3] 황종빈 과제 제출합니다.

code/gaeun011225/session2_3/연관분석 과제.ipynb
험난한 과제 제출기... 유정이가 도와줘서 덕분에 깃허브 오류를 해냈습니다...ㅜㅜ
연관분석 과제를 통해 1차인콘에서는 transaction데이터에서 찾지 못했던 패턴을 새로 발견할 수 있어서 흥미로웠습니다
특히, 연관분석은 처음 생긴 세션이라서 기대가 컸는데 잘 준비해주셔서 감사합니다 ㅎㅎ
=> [session2_3]최가은 과제 제출합니다.

code/Louisrum/Session2_4/엄태림_딥러닝(1)_과제.ipynb
제가 심리학과다 보니 생물이나 신경심리 수업을 나름 많이 들었어요.
그래서 뉴런의 구조나 시냅스를 통해 다음 뉴런으로 신호가 전달되는 과정은 익숙하거든요?
그래서 이번 딥러닝 세션을 들으면서
‘혹시 그 지식이랑 연계되는 부분이 있을까?’ 하고 내심 기대를 좀 했는데,
막상 그런 내용은 없더라구요…
이번 세션에서 딥러닝은, 입력받은 신호를 어떻게 처리해서 다음으로 넘겨줄지
또 얼마나 강하게 넘길지를 정하는 일종의 의사결정 과정처럼 느껴졌어요.
그치만 그 과정은 아직까지 온전히 이해가 되질 않네요.
전 항상 언어적으로는 이해가 되는데
수식적으로 표현된 부분은 이해가 잘 안되더라고요
딥러닝 공부와 더불어 수학 공부의 필요성을 느낍니다.
그리고 진짜 이런 걸 처음 고안해낸 사람들은 얼마나 똑똑하고
또 얼마나 변태같은 사람들일까 싶네요
어려운 내용 잘 정리해주셔서 감사합니다
앞으로 딥러닝 공부할 때 이 강의자료를 바탕으로 해서
길을 좀 찾아가봐야겠네요
고생하셨어요!
=> [session2_4] 엄태림 과제 제출합니다.

code/hyunji1122/session2_4/딥러닝(1)_과제_신현지.ipynb
축제소리때문에 진행할 때 곤란하셨을텐데,, 너무 수고 많으셨습니다😭
작년에 딥러닝개론 수업을 들었어서인지 생각보다 어렵지 않게 실습과 과제를 해낼 수 있었습니다 하하
딥러닝개론 중간고사 기말고사 생각도 나고,, 좋았습니다..ㅎㅎ
CNN 내용을 포함한 2차시 내용도 너무너무 기대가 되는군요!!! 제가 만약 한학기 더 활동할 수 있다면 심화세션으로 딥러닝을 선택할 거 같아요 ㅎㅅㅎ 중요하고 흥미로운 내용인 만큼, 열심히 집중해서 듣겠습니당!!! 화이팅 ٩(ˊᗜˋ*)و
=> [session2_4] 신현지 과제 제출합니다.

code/julv0207/session2_4/딥러닝(1)_과제ipynb_김진형.ipynb
딥러닝 실습시간에 배운 내용을 바탕으로 과제에서 직접 해보는 시간을 가져서 좋았습니다. 다양한 옵티마이저 중 Adam을 다뤄봤는데 상황에 맞게 다른 옵티마이저들도 해보고싶다는 생각이 들었습니다. 어려운 내용인만큼 꾸준한 복습이 필요하다고 생각해서 열심히 공부하겠습니다!! 다음 세션 cnn 기대됩니다 ㅎㅎ
=> [session2_4] 김진형 과제 제출합니다.

code/yseo17/session2_4/딥러닝(1)_과제.ipynb
이번 딥러닝 개념은 지금까지 몇번 다루어봤던 내용이라 익숙했지만, 실습 부분에서는 약하다고 느껴 이번 기회에 mnist 모델 학습을 해볼 수 있었습니다. 개념 부분도 이전부터 연쇄 법칙과 역전파 부분을 이해하는 데에 특히 시간이 오래 걸렸던 기억이 있는데요, 이번 세션에서는 술 마시고 차인다는 비유가 재밌어서 축제 소리에도 재밌게 들을 수 있었습니다. 
과제는 실습을 복습하는 느낌으로 진행했는데, Adam 옵티마이저는 배워만 봤지 실제로 사용해본 건 이번이 처음이었네요! 과제 중에 성능 차이가 궁금해서 Adam 대신 SGD로도 한번 돌려보니 예측 정확도가 97%로 큰 차이가 나지 않더라고요.
이런 경우는 mnist 데이터셋이 비교적 단순하기 때문일까요? 또 더 크거나 복잡한 데이터/모델에서는 SGD는 수렴 속도가 느리거나 local minima에 빠질 가능성이 높아 Adam이 유리하다는 의미로 이해하면 될지 궁금합니다~
=> [session2_4] 김윤서 과제 제출합니다.

code/Goals8942/Session2_4/딥러닝 과제.ipynb
딥러닝에 대한 심화적인 내용을 처음 접해 봤는데, 굉장히 흥미롭고 어려웠습니다. 
많은 부분들을 아직 완벽히 이해하지 못했지만, 그래도 인공 신경망이라는 아이디어 실현의 흐름은 이번 교육 세션, 실습, 과제를 진행하면서 느낌적으로 이해해 가는 것 같습니다. 다음 2번째 교육 세션도 기대가 됩니다, 집중해서 듣고 따라가 보겠습니다 !!
과제를 진행하면서, 마지막 실습 코드를 반복해서 돌렸을 때 모델의 정확도가 최저 5~60%대까지 내려가기도 하고, epoch 당 Cost가 매우 높아지기도 하고, 마지막 문제를 못 맞히는 경우도 발생했습니다. 같은 코드를 계속해서 돌렸는데, 이 정도로 모델 성능 차이가 나면 어떻게 하나 싶어서 문제 해결을 해보려고 마지막에 이거 저거 과정을 한 번 추가해 봤습니다. 
결과적으로, GPT의 도움을 받은 모델 학습 과정 개선(epoch 수 증가, Adam 학습률 감소)을 통해 모델 예측 정확도를 약 97%까지 올려 보았습니다. 딥러닝은 역시 대단한 거 같습니다.👍 빨리 더 배우고 싶습니다.
=> [session2_4] 윤해민 과제 제출합니다.

code/ba2slk/session2_4/딥러닝1_과제.ipynb
딥러닝 과제 제출합니다! 딥러닝 이론을 강의자료와 실습 코드를 통해 복습할 수 있어서 유익했습니다. 2차 딥러닝 세션도 기대하겠습니다 ~~
=> [session2_4] 배승식 과제 제출합니다.

code/i-am-jsung/session2_4/딥러닝(1)_과제답안.ipynb
딥러닝(1) 세션, 과제 준비하시느라 정말 수고 많으셨습니다. 많은 내용들이 담겨 있었는데 너무 유익하고 도움되는 내용들이였습니다~
딥너링은 공부할 수록 정말 흥미로운 분야인 것 같습니다. 실습과 과제를 통해 mnist 숫자 사진 데이터를 맞추는 과정도 직접 모델을 만들어보며 경험해 볼 수 있어서 너무 좋았습니다. 이제 활성함수, 손실함수, layer 구조 등을 바꿔가며 다양한 데이터에 대해 딥러닝 모델을 만들 수 있을 것 같고 다양한 데이터셋에 대해서 적용해 볼 수 있을 것 같습니다.
=> [session2_4] 김재성 과제 제출합니다.

code/suyeonlee01/session2_4/딥러닝(1)_과제.ipynb
작년 심화세션 때 딥러닝을 맡아 공부하여 발표하면서도 이해되지 않은 부분들이 있었는데, 이번 시간 발표를 듣고 더 자세하게 알게되었습니다. 
발표 자료도 훨씬 깔끔하게 잘 정리하신 것 같아요. 정말 좋았습니다. 
다음 세션 어려울 것 같지만.. 예습 최대한 해서 많이 얻어갈 수 있도록 하겠습니당
다음 시간도 화이팅입니다!
=> [session2_4] 이수연 과제 제출합니다

code/mingsaaa/session2_4/딥러닝(1)_과제.ipynb
지금 듣고 있는 인공지능과 경영모델 수업에서 배웠던 내용이 나와서 괜히 반가웠네요..ㅎ 
수업시간에는 솔직히 잘 이해 못하고 넘어갔는데 이렇게 세션에서 한번더 복기하니 확실히 처음보다 이해가 잘 갔던 것 같습니다!! 딥러닝... 여전히 어려운 개념이지만 다음 딥러닝 두번째 세션도 열심히 하겠습니다!
자료 만드느라 수고하셨어요~!
=> [session2_4] 김민지 과제 제출합니다. 

code/shtmdgur/session2_4/딥러닝(1)_과제.ipynb
아무래도 딥러닝은 이전의 세션에 비해 내용이 어려웠는데, 노션 페이지와 실습, 과제를 통해 원활하게 학습할 수 있었습니다.
과제를 통해 숫자를 예측하고 평가해보는 과정을 거쳤는데, 기존에 쓰던 모델들보다는 확실히 성능이 높게 나오네요.
이를 통해 다른 분야나 다른 문제에서도 딥러닝을 통해 무언가를 구현하거나 문제를 해결해보고 싶다는 생각이 들었습니다.
세션 준비하시느라 수고 많으셨습니다 ~
=> [session2_4] 노승혁 과제 제출합니다.

code/zzuhi/session2_4/딥러닝(1)_과제.ipynb
딥러닝 여전히 어려운 내용이지만.. 완벽한 설명과 실습자료 덕분에 조금씩 익숙해지고 있는 것 같아요 ㅎㅎ
다음 세션 예습도 열심히 하겠습니다 🫡 준비하느라 고생 많으셨어요!
=> [session2_4] 김주희 과제 제출합니다.

code/Allenkeem/session2_4/딥러닝(1)_과제_김찬우.ipynb
[딥러닝_1차시]
딥러닝 내용들 상당히 어려울 것이라고 생각하고 긴장하며 세션 들었는데, 워낙 자료와 실습을 준비 잘해주셔서 이해가 잘 되었던 것 같습니다. 어떤 숫자인지 예측해보는 모델을 과제를 통해 만들어보았는데, 상당히 흥미로웠습니다. 추후 이런 개념들이 어떻게 응용될지 기대가 됩니다. 딥러닝 2차시에도 집중 잘해서 열심히 해보겠습니다~!
세션 준비하느라 수고하셨습니다!
=> [session2_4] 김찬우 과제 제출합니다.

code/gaeun011225/session2_4/딥러닝 1차시 과제.ipynb
딥러닝 1차시 세션에서 어려운 내용을 쉽게 쉽게 설명해주시려고 한 것 같아서 세션 진행할 때랑 혼자 복습할 때 잘 이해할 수 있었습니다 ㅎㅎ
물론 아직 딥러닝과 친해지고 있는 중이지만.. 덕분에 잘 따라가고 있는 것 같습니당
딥러닝 2차시도 완전 기대중이에요 ~~~
=> [session2_4] 최가은 과제 제출합니다.

code/yyellow14/session2_4/딥러닝(1)_과제.ipynb
딥러닝 2차시가 기대가 됩니다! 딥러닝이 응용이 참 많이 될 수 있는 이론인데 이번 1차시를 통해 딥러닝의 기초를 잘 다질 수 있었던 것 같습니다 😊
=> [session2_4] 황종빈 과제 제출합니다.

code/Minhui21/session2_3/딥러닝(1)_과제.ipynb
딥러닝은 다시 배워도 너무 어렵군요 . . . . 그치만 노션 정리, 실습, 과제까지 중요한 포인트를 짚어서 반복해주셔서 이제는 딥러닝의 ㄷ까진 확실하게 알게 된 것 같아요,,,ㅎㅎ 정말 고생 많으셨습니다!!! 특히 한결오빠,,, 축제 중에도 한참을 발표하느라 정말 수고하셨어요,,,,,ㅠㅠ! 다음 cnn 세션은 제대로 배우는 게 처음이라 정말 기대가 됩니당 ><! 파이팅!
=> [session2_4] 김민희 과제 제출합니다.

code/55eona/sesson2_4/딥러닝(1)_과제.ipynb
과제에서 제시된 방식대로 크로스 엔트로피 손실 함수와 Adam 최적화 알고리즘을 사용했는데 계산된 손실 값과 테스트 데이터에서의 예측 정확도가 원래 주어진 결과와 달라, 원래 시도할 때마다 결과가 달라지는 것이 일반적인지 궁금해졌습니다.
=> [Sesson2-4] 문선아 과제 제출합니다.

code/Soovni/session2_4/딥러닝(1).ipynb
딥러닝 (2) 부분 발표하기 전에 과제파일 돌려보면서 사전 점검하는 시간을 가졌습니다~! 
의미있는 시간이었습니다!
=> [session2_4] 이수빈 과제 제출합니다

code/Jonghyun777/session2_4/딥러닝(1)_과제_이종현.ipynb
강의를 통해 딥러닝에 대해 많이 이해할 수 있었던 것 같습니다. 다만 내용이 워낙 어려워서 이해하는 것이 조금 힘들었지만 실습 과제를 하면서 세션 시간에 이해하지 못했던 부분까지 이해하는 데 도움이 되었던 것 같습니다. 특히 손실함수를 통해 모델이 예측한 값과 실제 값 간의 차이를 정량적으로 표현하며, 이를 기반으로 모델이 학습 방향을 결정한다는 점이 인상적이었습니다. 내일 두번째 딥러닝 세션도 완벽하게 이해하기 위해 노력해야 될 것 같네요!!
=> [session2_4] 이종현 과제 제출합니다.

code/dianner21/session2_4/딥러닝(1)_과제.ipynb
딥러닝의 기본 구조와 작동 원리에 대해 알게 되었습니다.
손글씨 숫자 분류 모델을 코드로 구현해보니 세션 때 이론으로 배운 부분이 훨씬 명확하게 와닿았습니다.
처음에 아무 생각 없이 학습 부분을 여러번 돌리다 정확도가 점점 떨어져서 당황했는데,
이럴 땐 모델과 옵티마이저를 재초기화해야 한다는 사실도 알게되었습니다..
2차 인콘 주제에 CNN이 있는데, CNN을 사용하면 성능이 얼마나 향상될지 기대됩니다!
=> [session2_4] 이지현 과제 제출합니다.

code/Jamesmoon00/session2_4/딥러닝(1)_과제.ipynb
2차시 준비하면서 사실 이미 실습이랑 과제 코드를 다 보기도 했는데,
2차시 내용을 생각하고 1차시 실습이랑 과제 내용이 딥러닝 입문에 대한 내용으로 정말 좋은 것 같다는 생각을 했습니다!
=> [session2_4] 문건우 과제 제출합니다.

code/55eona/sesson2_7/NLP_2차_과제_빈칸.ipynb
매일 사용하던 GPT의 동작 원리를 직접 학습하게 되어 미로웠다. 제로 어떻게 토큰화를 하고, 텍스트를 예측하는지 내부 과정을 이해할 수 있었던 점이 인상 깊었다. 특히 과제에서는 BERT와 GPT 모델을 활용하여 토큰을 예측하고, 다음 단어를 예측하는 실습을 진행하며 재미있게 배울 수 있었다. 2차 인사이콘에서도 NLP 관련 내용을 배우게 될 것 같은데 이번 학습을 통해 기초 개념과 실습 경험을 함께 쌓을 수 있어서 좋았다.
=> [sesson 2-7] 문선아 과제 제출합니다

code/Allenkeem/session2_7/NLP2_과제_빈칸_김찬우.ipynb
[NLP 2차시]
이번 NLP 세션 역시 상당히 잘 들었습니다. 사실 교육 세션 진행되면서 한번에 개념이 와닿는 느낌은 아니었습니다. 아마 심화세션을 좀 정리해가면서 들었어야 했는데 한번 밀리면서 쌓인 것이 지금에 와서 타격이 온 것 같아요. 이번 주에는 확실히 정리를 할 필요를 느낍니다.
집 돌아와서 코드와 개념을 함께 보면서는 이해가 되기 시작한 것 같습니다. NLP가 사실 좀 무궁무진하게 사용될 수 있는 느낌인데, 어떻게 활용할 수 있을지에 대한 방안을 제 스스로 더 생각해볼 수 있게 된 것 같아요.
이제 다음 세션은 시계열인데, 기대가 많이 됩니다. 어떤 내용들이 준비되었을지 궁금해요.
별개로 과제를 통해서 저녁메뉴를 한번 추천 받아봤는데요. 떡볶이가 나와서 야무지게 먹어보도록 하겠습니다~!
이번 세션도 준비하느라 고생 너무 많으셨습니다. 감사하게 잘 들었어요! 😆
=> [session2_7] 김찬우 과제 제출합니다.

NLP2_과제_빈칸.ipynb
nlp 과제 너무 재밌게 했습니다! 문장 생성하는게 되게 재밌네요ㅎㅎ 소설쓰는 gpt 확인할 수 있었습니다! 
자료 만드느랴 고생많으셨습니다.!!
=> [session2_7] 이수빈 과제 제출합니다.

code/julv0207/session2_7/NLP2_과제_빈칸_김진형.ipynb
nlp 1,2차시 모두 만족스럽게 들었습니다. 과제도 재밌었어요 ㅎㅎ 이제 마지막 시계열 세션만 남아서 아쉽네요 인사이트 파이팅 ㅜㅜㅜㅜ
=> [session2_7] 김진형 과제제출합니다.

code/suyeonlee01/session2_7/NLP2_과제_빈칸.ipynb
이번 NLP 심화세션 발표를 너무 잘 해주셔서 이해하기 좋았던 것 같아요 고생 많으셨습니다 ㅎㅎ
과제 중에 [MASK] 찾아내는 부분에서 자꾸 오류가 나더라구요
지피티랑 열심히 대화도 해봤는데 해결을 못해서 일단 제출합니다 ㅠㅠ
봐주시면 감사하겠습니당
=> [session2_7] 이수연 과제 제출합니다

code/Jonghyun777/session2_7/NLP2_과제_빈칸_이종현.ipynb
nlp 2차 들으면서 내용이 너무 어려워서 걱정했었는데 과제를 하면서 조금씩 이해가 되는 것 같습니다. MLM을 사용해서 문장 만드는 것도 너무 재밌었고 긍정,중립,부정으로 출력되는 것도 너무 신기했습니다. nlp세션 준비하신 분들 고생많으셨습니다~~
=> [session2_7] 이종현 과제 제출합니다.

code/Louisrum/session2_7/엄태림_NLP2_과제_빈칸.ipynb
NLP 너무 어려워서 중간에 영혼이 나갔습니다
그래도 정말 매력적이고, 또 유용한 기술임에는 틀림없으니
열심히 공부를 해서 익혀보도록 하겠습니다.
과제를 통해서 BERT와 GPT 모델의 구동을 직접 해봤는데요
직접 문장을 만들고, 모델이 작업을 해서 결과물을 보는 과정이 재밌더라구요
BERT로 13기 회장에 가장 적합한 사람이 누구냐고 물어봤는데 
자꾸 문재인씨가 나와서 너무 당황했네요
다행히 학회원들 성을 빼고 이름만 넣고 돌려보니
지현이가 13기 회장에 적합하다는 아주 만족스러운 결과물을 얻을 수 있었습니다.
2차인콘 우승팀 주제가 뭐일거 같냐고 예측 시켜보니까 이상한 소리만 하길래
GPT2는 성능이 상당히 떨어진다는 점을 다시 한 번 느낄 수 있었습니다.
=> [session2_7] 엄태림 과제 제출합니다.

code/Minhui21/session2_7/NLP_2차시_과제_빈칸.ipynb
NLP는 왜 두 번 배워도 어려울까요....
그치만 탄탄하게 자료 만들어주신 덕분에 필요할 때마다 찾아서 더 공부해볼 수 있을 것 같습니다,,,ㅠ
다들 어려운 내용 쉽게 설명해주시느라 고생 많으셨습니다!
=> [session2_7] 김민희 과제 제출합니다.

code/shtmdgur/session2_7/NLP2_과제_빈칸.ipynb
nlp 너무 어려워요
과제를 통해 bert 모델을 학습시키고, 예시 문장을 넣어 mlm 방식으로 마스크로 가린 단어를 예측해보도록 했습니다.
맞는 답을 내지는 않았지만 그래도 코드 흐름을 파악하고 예시 문장을 통해 활용하는 것 까지는 해볼 수 있어서 좋다고 느꼈습니다.
뉴스 기사 제목을 중립/긍정/부정으로 분류도 해보고, GPT로 문장도 생성하는 과정을 실행해 볼 수 있었는데, 분류는 잘 하는데 GPT는 옛날 모델을 사용해서 별로 상관 없는 말을 하네요.
개념에 대해서 이해는 못했지만, 코드 흐름에 대해서만 알고 넘어가고 나중에 쓸 일이 있으면 돌아와서 참고하는 정도만 되도 좋지 않을까 .. 생각합니다.
세션 준비하느라 수고하셨습니다!
=> [session2_7] 노승혁 과제 제출합니다.

code/il-ho-kim/session2_7/NLP2_과제_김일호.ipynb
세션 들으면서는 정신이 혼미했지만,,,
과제와 실습 문제 풀면서 본질과 기능에 집중을 해보니 그래도 돌아가는 태 정도는 깨달을 수 있었던 것 같습니다...!
GPT와 BERT의 학습 접근법도 예시를 통해 재미있게 배울 수 있었습니다! 수고하셨어요!
=> [session2_7] 김일호 과제 제출합니다.
